#!/bin/env bash
black="\e[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
background="\033[0m"

GithubMirror="https://mirror.ghproxy.com/"

if [ "$(uname -o)" = "Android" ]; then
	echo "看来你是大聪明 加Q群获取帮助吧 596660282"
	exit 1
fi

if ! [ "$(uname)" == "Linux" ];then
    echo -e ${red}请使用linux!${background}
    exit 0
fi

echo -e ${white}"====="${green}白狐-Script${white}"====="${background}
echo -e ${cyan}ArcticFoxScript ${green}是完全可信的。${background}
echo -e ${cyan}ArcticFoxScript ${yellow}不会执行任何恶意命令${background}
echo -e ${cyan}ArcticFoxScript ${yellow}不会执行任何恶意命令${background}
echo -e ${cyan}ArcticFoxScript ${yellow}不会执行任何恶意命令${background}
echo -e ${cyan}如果您同意安装 请输入 ${green}同意安装${background}
echo -e ${cyan}注意：同意安装即同意本项目的用户协议${background}
echo -e ${cyan}用户协议: ${background}
echo -e ${yellow}正在获取${background}
curl -sL https://github.com/ArcticFox520/Yunzai-Bot-Script/raw/main/用户协议.txt
echo -e ${white}"=========================="${background}
echo -en ${green}请输入:${background};read yn
if [ ! "${yn}" == "同意安装" ]
then
    echo -e ${red}程序终止!! 脚本停止运行${background}
    exit
fi

if [ $(command -v apt) ];then
  if ! dpkg -s git > /dev/null 2>&1;then
    apt install -y git
  fi
if [ $(command -v apt-get) ];then
  if ! dpkg -s git > /dev/null 2>&1;then
    apt-get install -y git
  fi
elif [ $(command -v yum) ];then
  if ! yum list installed git > /dev/null 2>&1;then
    yum install -y git
  fi
elif [ $(command -v dnf) ];then
  if ! dnf list installed git > /dev/null 2>&1;then
    dnf install -y git
  fi
elif [ $(command -v pacman) ];then
  if ! pacman -Qi git > /dev/null 2>&1;then
    pacman -S --noconfirm --needed git
  fi
elif [ $(command -v pkg) ];then
  if ! dpkg -s git > /dev/null 2>&1;then
    pkg install -y git
  fi
fi

URL="https://ipinfo.io"
Address=$(curl -sL ${URL} | sed -n 's/.*"country": "\(.*\)",.*/\1/p')
if [ "${Address}" = "CN" ]
then
  GitMirror="${GithubMirror}/https://github.com"
else
  GitMirror="https://github.com"
fi

AFHOME="$(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
OldHOME=$(grep AFHOME $AFHOME/Manage/config)
sed -i "s|$OldHOME|AFHOME=$AFHOME|g" $AFHOME/Manage/config
echo -e ${blue}[${green}*${blue}] AFYBS根目录已更改为 ${yellow}$AFHOME${background}
Command="bash $AFHOME/Manage/Main.sh $AFHOME"
if [ -e /usr/local/bin/afmc ];then
  rm /usr/local/bin/afmc
fi
cp $AFHOME/afyz /usr/local/bin/afyz
sed -i "s|Command|${Command}|g" /usr/local/bin/afyz
sed -i "s|PATH|$AFHOME|g" /usr/local/bin/afyz
chmod +x /usr/local/bin/afmc

echo -e ${yellow} - ${yellow}安装成功${background}
echo -e ${yellow} - ${cyan}请使用 ${green}afyz ${cyan}命令 打开脚本${background}