#!/bin/env bash
black="\e[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
background="\033[0m"

GithubMirror="https://mirror.ghproxy.com"

function Download(){
file="$1"
URL="$2"
local i=0
if wget --help | grep -q show-progress 
then
  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
  until wget -q --show-progress -O ${file} -c ${URL}
  do
    if [ ${i} == 3 ]
    then
      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
      return 1
    fi
    i=$((${i}+1))
    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成.${background}
  return 0
else
  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
  until wget -O ${file} -c ${URL}
  do
    if [ ${i} == 3 ]
    then
      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
      return 1
    fi
    i=$((i+1))
    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成.${background}
  return 0
fi
}

echo -e ${green}正在修改 ${yellow}DNS配置${background}
rm /etc/resolv.conf
echo 'nameserver 223.5.5.5
nameserver 223.6.6.6
nameserver 2400:3200::1
nameserver 2400:3200:baba::1' > /etc/resolv.conf
cat /etc/resolv.conf
echo -e ${green}已修改为 ${yellow}阿里DNS${background}

echo -e ${green}正在修改 ${yellow}Pacman仓库源${background}

echo '
##
## MSYS2 repository mirrorlist
##

## Primary
## msys2.org
Server = https://mirrors.bfsu.edu.cn/msys2/msys/$arch
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/$arch
Server = https://mirror.nju.edu.cn/msys2/msys/$arch
Server = https://mirrors.aliyun.com/msys2/msys/$arch
Server = https://mirror.msys2.org/msys/$arch
Server = https://repo.msys2.org/msys/$arch
' > mirrorlist.msys

cat > mirrorlist.mingw64 <<- FOX
##
## 32-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
Server = https://mirrors.bfsu.edu.cn/msys2/msys/x86_64
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64
Server = https://mirror.nju.edu.cn/msys2/msys2/msys/x86_64
Server = https://mirrors.aliyun.com/msys2/msys/x86_64
Server = https://mirror.msys2.org/msys/x86_64
Server = https://repo.msys2.org/msys/x86_64
FOX

cat > mirrorlist.mingw32 <<- FOX
##
## 32-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
Server = https://mirrors.bfsu.edu.cn/msys2/msys/i686
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/i686
Server = https://mirror.nju.edu.cn/msys2/msys/i686
Server = https://mirrors.aliyun.com/msys2/msys/i686
Server = https://mirror.msys2.org/msys/i686
Server = https://repo.msys2.org/msys/i686
FOX

cat > mirrorlist.clang64 <<- FOX
## Primary
Server = https://mirrors.bfsu.edu.cn/msys2/mingw/clang64
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/clang64
Server = https://mirror.nju.edu.cn/msys2/mingw/clang64
Server = https://mirrors.aliyun.com/msys2/mingw/clang64
Server = https://mirror.msys2.org/mingw/clang64
Server = https://repo.msys2.org/mingw/clang64
FOX

cat > mirrorlist.clang32 <<- FOX
## Primary
Server = https://mirrors.bfsu.edu.cn/msys2/mingw/clang32
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/clang32
Server = https://mirror.nju.edu.cn/msys2/mingw/clang32
Server = https://mirrors.aliyun.com/msys2/mingw/clang32
Server = https://mirror.msys2.org/mingw/clang32
Server = https://repo.msys2.org/mingw/clang32
FOX

cat > mirrorlist.ucrt64 <<- FOX
## Primary
Server = https://mirrors.bfsu.edu.cn/msys2/mingw/ucrt64
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/ucrt64
Server = https://mirror.nju.edu.cn/msys2/mingw/ucrt64
Server = https://mirrors.aliyun.com/msys2/mingw/ucrt64
Server = https://mirror.msys2.org/mingw/ucrt64
Server = https://repo.msys2.org/mingw/ucrt64
FOX

mv mirrorlist.msys /etc/pacman.d/mirrorlist.msys
mv mirrorlist.mingw64 /etc/pacman.d/mirrorlist.mingw64
mv mirrorlist.mingw32 /etc/pacman.d/mirrorlist.mingw32
mv mirrorlist.clang64 /etc/pacman.d/mirrorlist.clang64
mv mirrorlist.clang32 /etc/pacman.d/mirrorlist.clang32
mv mirrorlist.ucrt64 /etc/pacman.d/mirrorlist.ucrt64
cat /etc/pacman.d/mirrorlist.msys
echo -e ${green}修改完成${background}

echo -e ${green}正在更新 ${yellow}MSYS2${background}
pacman -Syyu --noconfirm
echo -e ${green}更新完成${background}

echo -e ${green}正在安装 ${yellow}依赖软件${background}
pacman -S --needed --noconfirm tar gzip xz tmux screen curl wget pv git redis jq chromium ffmpeg
echo -e ${green}安装完成${background}

if [ ! -x "$(command -v pnpm)" ];then
    echo -e ${green}正在安装 ${yellow}PNPM${background}
    a=0
    npm config set registry ${NPMMirror}
    npm config set registry ${NPMMirror}
    npm install -g npm@latest
    until npm install -g pnpm@latest
    do
      if [ "${a}" == "3" ];then
        echo -e ${red}错误次数过多 退出${background}
        exit
      fi
      echo -e ${red}pnpm安装失败 ${green}正在重试${background}
      a=$(($a+1))
    done
    echo
fi
echo -e ${yellow}正在为pnpm更换默认源${background}
pnpm config set registry ${NPMMirror}
pnpm config set registry ${NPMMirror}

until pnpm install -g pm2@latest
do
  if [ "${a}" == "3" ];then
    echo -e ${red}错误次数过多 退出${background}
    exit
  fi
  echo -e ${red}pnpm安装失败 ${green}正在重试${background}
  a=$(($a+1))
done
