#!/bin/env bash
#
black="\e[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
background="\033[0m"

GithubMirror="https://gh.arcticfox.top"

apt_update(){
if [ "${apt_update}" != "apt_updated" ]
then
  echo -e ${green}正在更新 ${yellow}软件源${background}
  if apt update -y
  then
    echo -e ${red}更新出错${background}
    exit 1
  fi
  apt_update=apt_updated
fi
}

Package=("tar" "gzip" "xz-utils" "tmux" "screen" "wget" "curl" "pv" "git" "redis-server" "chromium")
for PKG in ${Package[@]}
do
  if ! dpkg -s ${PKG} >/dev/null 2>&1
  then
    echo -e ${green}正在安装 ${yellow}git${background}
    apt_update
    until apt install -y ${PKG}
    do
      echo -e ${red}安装失败 3秒后重试${background}
      sleep 3s
    done
    echo -e ${green}安装完成${background}
  fi
done

Command(){
i=0
until bash AFYZ/Install/$1
do
  if [ ${i} -eq 3 ]
    then
      echo -e ${red}错误次数过多 退出${background}
      exit 1
  fi
  i=$((${i}+1))
  echo -en ${red}命令执行失败 ${green}3秒后重试${background}
  sleep 3s
done
}

for file in ("NodeJS" "FFmpeg" "yq")
do
  Command ${file}
done