#!/bin/env bash
#
black="\e[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
background="\033[0m"

GithubMirror="https://gh.arcticfox.top"

function Download(){
file="$1"
URL="$2"
local i=0
if wget --help | grep -q show-progress 
then
  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
  until wget -q --show-progress -O ${file} -c ${URL}
  do
    if [ ${i} == 3 ]
    then
      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
      return 1
    fi
    i=$((${i}+1))
    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成.${background}
  return 0
else
  echo -e ${blue}[${green}*${blue}] ${cyan}正在下载 ${yellow}${file}${cyan}${background}
  until wget -O ${file} -c ${URL}
  do
    if [ ${i} == 3 ]
    then
      echo -e ${blue}[${red}*${blue}] ${cyan}错误次数过多 ${yellow}退出${background}
      return 1
    fi
    i=$((i+1))
    echo -e ${blue}[${red}*${blue}] ${cyan}下载失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
  echo -e ${blue}[${green}*${blue}] ${cyan}下载完成.${background}
  return 0
fi
}

apt_update(){
if [ -z ${apt_update} ]
then
  echo -e ${green}正在更新 ${yellow}软件源${background}
  if ! apt update -y
  then
    echo -e ${red}更新出错${background}
    exit 1
  fi
  apt_update=apt_updated
fi
}

Package=("tar" "gzip" "xz-utils" "tmux" "screen" "wget" "curl" "pv" "git" "redis-server" "gnupg" "jq")
for PKG in ${Package[@]}
do
  if ! dpkg -s ${PKG} >/dev/null 2>&1
  then
    echo -e ${green}正在安装 ${yellow}${PKG}${background}
    apt_update
    until apt install -y ${PKG}
    do
      echo -e ${red}安装失败 3秒后重试${background}
      sleep 3s
    done
    echo -e ${green}安装完成${background}
  fi
done 

if which chromium >/dev/null 2>&1 || which chromium-browser >/dev/null 2>&1
then
  exit 0
fi

if [ ! -d /etc/apt/sources.list.d ]
then
  mkdir -p /etc/apt/sources.list.d
fi

touch /etc/apt/sources.list.d/ppa.sources.list

if grep -q -i focal /etc/os-release
then
  UbuntuVersion="focal"
elif grep -q -i jammy /etc/os-release
then
  UbuntuVersion="jammy"
elif grep -q -i noble /etc/os-release
then
  UbuntuVersion="noble"
else
  echo -e ${red}不受支持的发行版${background}
  exit 1
fi

echo -e ${green}正在写入 ${yellow}PPA仓库${background}
PPA="deb https://ppa.arcticfox.top/xtradeb/apps/ubuntu ${UbuntuVersion} main"
echo ${PPA} > /etc/apt/sources.list.d/ppa.sources.list

echo -e ${green}正在获取 ${yellow}仓库密钥${background}
SigningKeyFingerprintURL="https://launchpad.arcticfox.top/~xtradeb/+archive/ubuntu/apps"
SigningKeyFingerprint=$(curl ${SigningKeyFingerprintURL} | grep "signing_key_fingerprint" | sed 's|<script id="json-cache-script">LP.cache =||g' | sed 's|;</script>||g' | jq .context.signing_key_fingerprint | sed 's|"||g')
if [ -z ${SigningKeyFingerprint} ]
then
  SigningKeyFingerprint=5301FA4FD93244FBC6F6149982BB6851C64F6880
fi

echo -e ${green}正在导入 ${yellow}仓库密钥${background}
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${SigningKeyFingerprint}
apt update -y
echo -e ${green}开始安装chromium${background}
if apt install -y chromium
then
  echo -e ${green}安装完成${background}
fi